@ Generated by gcc 3.0.2 (DevKit-Advance) for ARM/elf
	.file	"int_warp.c"
	.text
	.align	2
	.global	int_handler_warp
	.type	int_handler_warp,function
int_handler_warp:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, current_function_anonymous_args = 0

	# Save context start
	ldr	r3, .L2
	ldr	r3, [r3, #0]
	mov r0,r3
	stmia r0!,{sp}^
	ldr	r3, .L2
	ldr	r3, [r3, #0]
	add	r3, r3, #28
	mov r0,r3
	stmia r0!,{r4-r11}
	ldmfd sp!,{r4-r9}
	ldr	r3, .L2
	ldr	r3, [r3, #0]
	add	r3, r3, #4
	mov r0,r3
	stmia r0!,{r4-r9}
	# Save context end

	stmfd sp!,{lr}
	bl	GBAInterruptHandler
	ldmfd sp!,{lr}

	# Test end
	ldr	r3, .L2
	ldr	r3, [r3, #0]
	add	r3, r3, #4
	mov r0,r3
	ldmia r0!,{r4-r9}
	stmfd sp!,{r4-r9}
	ldr	r3, .L2
	ldr	r3, [r3, #0]
	add	r3, r3, #28
	mov r0,r3
	ldmia r0!,{r4-r11}
	ldr	r3, .L2
	ldr	r3, [r3, #0]
	mov r0,r3
	ldmia r0!,{sp}^
	# Switch end

	mov pc,lr
.L3:
	.align	2
.L2:
	.word	ScheduleState
.Lfe1:
	.size	int_handler_warp,.Lfe1-int_handler_warp
