@ Generated by gcc 3.0.2 (DevKit-Advance) for ARM/elf
	.file	"thread_entry_thunk.c"
	.text
	.align	2
	.global	__thread_entry_thunk
	.type	__thread_entry_thunk,function
__thread_entry_thunk:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 0, current_function_anonymous_args = 0
	ldmfd sp!,{r3}
	mov r0,r3
	bl	__thread_entry
.Lfe1:
	.size	__thread_entry_thunk,.Lfe1-__thread_entry_thunk
	.comm	ThreadList, 88	@ 88
